development:
  adapter: postgresql
  database: movie-reviews-development
  pool: 5
  timeout: 5000
  username: postgres
  password: password

production:
  adapter: postgresql
  database: movie-reviews-production
  pool: 5
  timeout: 5000